{% set docker_config = {
  "auths": {
    ecr_url: {
      "username": "AWS",
      "password": ecr_docker_pass,
      "auth": ("AWS:" + ecr_docker_pass) | b64encode,
    }
  }
} %}
---
apiVersion: v1
data:
  .dockerconfigjson: {{ docker_config | tojson | b64encode }}
kind: Secret
metadata:
  name: ecr-credentials
  namespace: example-app
type: kubernetes.io/dockerconfigjson

